### ISSUE TITLE
Usability - Letters are too bright

### ISSUE THREAD

**Issue by yzeng25** [fajita12/socialOctopus#30]
<img width="339" alt="screen shot 2018-05-02 at 1 14 25 pm" src="https://user-images.githubusercontent.com/36651058/39541267-d955f5f2-4e0a-11e8-992a-f03028a5fa13.png">

**Comment by agrimpandey** [comment]
This is an old branch which was not submitted for the testing assignment. Sorry for any confusion from our side. please refer to the branch bugfreestuff or the most latest one finaldemo1

**Comment by yzeng25** [comment]
Sure. Thanks for your update!

________________________________
