### ISSUE TITLE
Usability - 'Save draft' is not used

### ISSUE THREAD

**Issue by yzeng25** [fajita12/socialOctopus#32]
When editing a new post, user should be able to save this new post as a draft. But this app only offers two option: either click on 'post' to make a new post, or click on '<-' to go back to homepage and abandon the new post. If some users spend a lot of time editing and click on '<-' by accident, they would need to redo all the editing. 
When users has something in the post they are editing and they click '<-', the app should prompt the user to either save the draft or exit to homepage.
<img width="335" alt="screen shot 2018-05-02 at 1 36 02 pm" src="https://user-images.githubusercontent.com/36651058/39542335-e6d25b1e-4e0d-11e8-8c5f-70f35f05b839.png">

**Comment by agrimpandey** [comment]
resolved. code in finaldemo1
when back button is pressed draft is saved and draft is ready on return to post page again.
the post is saved. the title of the post is not saved because at this point we dont do anything with it so we worry about only the post.
