### ISSUE TITLE
Usability - Checkbox under Account selection

### ISSUE THREAD

**Issue by yzeng25** [fajita12/socialOctopus#33]
User are allowed to click on the checkbox only after they make selections in 'type'. 
<img width="341" alt="screen shot 2018-05-02 at 1 48 14 pm" src="https://user-images.githubusercontent.com/36651058/39542980-98df200c-4e0f-11e8-8438-acfc06dffed9.png">

**Comment by agrimpandey** [comment]
It looks like you are using the wrong branch. This branch was not submitted for the testing assignment.  Most latest code is in finaldemo1 after some changes based on bugs reported by your team. This is how the settings page looks like.
![image](https://user-images.githubusercontent.com/17019100/39552079-528722bc-4e2d-11e8-9715-524eac01946a.png)
