### ISSUE TITLE
Usability - limits on Quote

### ISSUE THREAD

**Issue by yzeng25** [fajita12/socialOctopus#38]
**Severity**: trivial 
**Description**: In 'settings' page, 'Quotes' section has no limitations of input (i.e. characters only, number only, special char like !@#$$%^^ allowed), which is totally fine. But there is no limitation on length of the 'Quote'
I randomly typed some characters to see if there are limitations
<img width="687" alt="screen shot 2018-05-02 at 11 48 12 pm" src="https://user-images.githubusercontent.com/36651058/39560989-4eb010f0-4e68-11e8-849a-049206da86f6.png">

869 characters but I can still type things in:
<img width="674" alt="screen shot 2018-05-02 at 11 47 59 pm" src="https://user-images.githubusercontent.com/36651058/39561018-78b17aa6-4e68-11e8-931a-aa87bf4ba04c.png">

2,910 characters but I can still type things in:
<img width="685" alt="screen shot 2018-05-03 at 12 00 50 am" src="https://user-images.githubusercontent.com/36651058/39561025-8deec73e-4e68-11e8-82e6-4cc0372afc38.png">

**Suggestion**: put a limitation on the length of 'Quote'.

**Comment by agrimpandey** [comment]
resolved. code in finaldemo1. quotes char limit is 60 chars now
