### ISSUE TITLE
Usability - Name cannot contain number, special characters, or other languages

### ISSUE THREAD

**Issue by yzeng25** [fajita12/socialOctopus#39]
**Severity**: trivial
**Description**:
In 'settings', 'name' cannot contain number, special characters or other languages. 

Name is 'testing' works.
<img width="686" alt="screen shot 2018-05-02 at 11 50 07 pm" src="https://user-images.githubusercontent.com/36651058/39561138-4b9b30ce-4e69-11e8-9fe1-c6f34c892648.png">

Name is 'testing1' does not work
<img width="684" alt="screen shot 2018-05-02 at 11 50 28 pm" src="https://user-images.githubusercontent.com/36651058/39561142-50c82318-4e69-11e8-84d3-584c578e5b8a.png">

Name is 'testing@' does not work.
<img width="688" alt="screen shot 2018-05-02 at 11 50 44 pm" src="https://user-images.githubusercontent.com/36651058/39561134-44e15538-4e69-11e8-9c6d-d3dd75a510c4.png">
Name is '哼' (a word in other language) does not work
<img width="688" alt="screen shot 2018-05-03 at 12 33 51 am" src="https://user-images.githubusercontent.com/36651058/39561205-def6a8a8-4e69-11e8-982b-eb6232dff248.png">

**Suggestion**: Maybe you should consider allowing numbers, special characters, and characters in other languages in 'Name'.

**Comment by agrimpandey** [comment]
Resolved. code in finaldemo1
